### ISSUE TITLE
Server Push Example

### ISSUE THREAD

**Issue by kevinswiber** [Voxer/iSPDY#24]
Hello.  I work on the Zetta IoT platform (https://github.com/zettajs/zetta).  We pretty heavily rely on node-spdy for our server-to-server protocol.  We're now looking at exposing SPDY for the client-to-server protocol, as well.  All that is looking fine from the server side, but when I started looking at iSPDY to evaluate updating our iOS client, I was having a bit of trouble figuring out how to get Server Push to work.  @mdobson has a lot more experience than I do on the iOS front, so perhaps he can help figure it out for Zetta, but for now, I'm stuck.

Could someone with iSPDY experience throw together a quick example of how to wire up handlers for Server Push?

Thanks!

**Comment by indutny** [comment]
Hello!

It is fairly simple:

```objc
@interface MyDelegate <ISpdyDelegate>
@end
```

```objc
@implementation MyDelegate

- (void) connection: (ISpdy*) conn handlePush: (ISpdyPush*) push {
  // Do something with push
}

@end
```

And usage:

```
ISpdy* s = [[ISpdy alloc] init: kISpdyV3 host: @"some.host" port: 443 secure: YES];
MyDelegate* d = [MyDelegate alloc];

[s setDelegate: d];
[s connect];
```

Note that it might require a little bit of tweaking. I didn't test it.

**Comment by kevinswiber** [comment]
Thanks. I tried something like this but couldn't get connection:handlePush to fire. I can see the response on the initial request. I just don't receive any pushed responses associated to that stream. I'll dig a little deeper.

**Comment by indutny** [comment]
No problem. I would suggest checking the server side, does it actually push anything? Is it possible to confirm it?

**Comment by kevinswiber** [comment]
Yes, the server is pushing to other SPDY clients (node-spdy). I'll confirm it's pushing over the iSPDY connection and do a deeper dive.

**Comment by kevinswiber** [comment]
Hmm.  So it looks like the delegate is getting assigned... and when [this line](https://github.com/Voxer/iSPDY/blob/master/src/ispdy.m#L1062) fires, the delegate does not exist.  I can't get any of the implemented methods of the delegate to fire, actually.  Compiling for iOS 8.3.

Any glaring mistakes here?

Delegate:
```objective-c
@interface SpdyHandler : NSObject<ISpdyDelegate,ISpdyLogDelegate>

@end

@implementation SpdyHandler

- (void) handleConnect: (ISpdy*) conn {
    NSLog(@"Handle connect");
}
- (void) connection: (ISpdy*) conn handleError: (ISpdyError*) err {
    NSLog(@"Handle error");
}
- (void) connection: (ISpdy*) conn handlePush: (ISpdyPush*) push {
    NSLog(@"Handle push");
    // [push setDelegate:[SpdyRequest alloc]];
}
- (void) logSpdyEvents: (ISpdy*) conn
                 level: (ISpdyLogLevel) level
               message: (NSString*) message {
    NSLog(@"Handle log");
}
```

Usage
```objective-c
ISpdy *conn  = [[ISpdy alloc] init:kISpdyV3 host:@"localhost" port:1337 secure:false];
SpdyHandler *del = [SpdyHandler alloc];
[conn setDelegate:del];
[conn connect];

ISpdyRequest *req = [[ISpdyRequest alloc] init: @"GET" url:@"/_pubsub/subscribe?topic=heartbeat%2Fc4c4a38f-3163-45e1-98ae-d142cc1f2d87%2Fpulse"];

[conn send:req];
```

**Comment by kevinswiber** [comment]
Never mind.  Delegate was going out of scope and getting deallocated, apparently.  My mistake!  Closing.
